.\Manpage pour dec2bin.sh.
.\Contact zoeurk.gmail.com
.TH man 1 "22 avril 2021" "1.0" "dec2bin.sh man page"
.SH NAME
dec2bin.sh \- Encode(/Decode) de(/vers) la base hexadecimal(/binaire)
.SH SYNOPSIS
dec2bin 2BIN|2DEC [VIRGULE] "value"
.SH DESCRIPTION
Encode(/decode) de(/vers) la base hexadecimal(/binaire)
.SH BUGS
Je sais pas
.SH AUTHORS
ZoeurK (zoeurk@gmail.com)
.SH SEE ALSO
ntest(1) calcule(1) decimal.sh (1) hex2bin.sh (1) dec2bin.sh (1)
