.\Manpage pour decimal.sh.
.\Contact zoeurk.gmail.com
.TH man 1 "22 avril 2021" "1.0" "decimal.sh man page"
.SH NAME
decimal.sh \- Encode(/Decode) de(/vers) la base decimal
.SH SYNOPSIS
decimal.sh HEX2BIN|BIN2HEX [VIRGULE] "value" base
.SH DESCRIPTION
Encode(/decode) de(/vers) la base decimal
.SH BUGS
Je sais pas
.SH AUTHORS
ZoeurK (zoeurk@gmail.com)
.SH SEE ALSO
ntest(1) calcule(1) hex2bin.sh(1) dec2bin.sh(1)
