all:

install:
	cp *.sh /usr/sbin/
	chmod 755 /usr/sbin/dec2bin.sh
	chmod 755 /usr/sbin/dec2hex.sh
	chmod 755 /usr/sbin/hex2bin.sh

uninstall-recursive:
	rm /usr/sbin/dec2bin.sh
	rm /usr/sbin/dec2hex.sh
	rm /usr/sbin/hex2bin.sh

