all:

clean:

install:
	cp *.sh /usr/sbin/
	chmod 755 /usr/sbin/dec2bin.sh
	chmod 755 /usr/sbin/dec2hex.sh
	chmod 755 /usr/sbin/hex2bin.sh
	chmod 755 /usr/sbin/decimal.sh

uninstall:
	rm /usr/sbin/dec2bin.sh
	rm /usr/sbin/dec2hex.sh
	rm /usr/sbin/hex2bin.sh
	rm /usr/sbin/decimal.sh


